;Universidad Rafael Landivar
;Arquitectura del Computador Ciclo II 2022

LIST P=16F877A
RADIX HEX
#INCLUDE <P16F877a.inc>
__CONFIG  _CP_OFF &_WDTE_OFF & _PWRTE_OFF & _HS_OSC & _CPD_OFF & _LVP_OFF & _BOREN_OFF & _WRT_OFF & _DEBUG_ON

;--------------Declaracion de varialbes--------------
R_UNIDADES EQU 0X20
R_DECENAS EQU 0X21
R_UNIDADES2 EQU 0X22
R_DECENAS2 EQU 0X23

POS1_UNIDADES EQU 0X30
POS1_DECENAS EQU 0X31

POS2_UNIDADES EQU 0X32
POS2_DECENAS EQU 0X33

CUAL_OPERACION EQU 0X34

RESPUESTA EQU 0X35
RESPUESTA_UNIDADES EQU 0X50
RESPUESTA_DECENAS EQU 0X51
RESPUESTA_UNIDADES2 EQU 0X52
RESPUESTA_DECENAS2 EQU 0X53


RESTACONT1 EQU 0X60
RESTACONT2 EQU 0X61
RESTACONT11 EQU 0X62
RESTACONT22 EQU 0X63


NUMCONT EQU 0X36
NUMERO1 EQU 0X37
NUMERO2 EQU 0X38

VALOR_TEMP EQU 0X39
VALOR_TEMP2 EQU 0X54

CONTADOR1 EQU 0X40
CONTADOR2 EQU 0X41
;------------Puertos-------------------------------
ORG 0
	CLRW
	BSF STATUS, RP0
	MOVLW 0X06
	MOVWF ADCON1
	MOVLW B'11111111' 
	MOVWF TRISA ;Puerta A va ser entrada 
	MOVLW B'11111111' 
	MOVWF TRISC ;Puerta C va ser entrada 
	BCF STATUS, RP0 
	
	CLRW
	BSF STATUS,RP0
	CLRF TRISB ;Pueta B va ser salida
	CLRF TRISD ;Pueta D va ser salida
	CLRF TRISE
	BCF STATUS,RP0

;--------------Comeinza codigo--------------
;---------------Contador--------------------
	MOVLW H'0'
	MOVWF R_UNIDADES
	MOVWF R_DECENAS
	MOVWF POS1_UNIDADES
	MOVWF POS1_DECENAS
	MOVWF CUAL_OPERACION

	MOVLW H'0'
	MOVWF POS2_UNIDADES
	MOVWF POS2_DECENAS

	MOVLW H'A'
	MOVWF R_UNIDADES2
	MOVWF R_DECENAS2

	MOVLW H'1'
	MOVWF CUAL_OPERACION
	MOVWF PORTE


	CICLO1
	GOTO VERIFICAROPERACION
	REGRESAR
	GOTO VERIFICARGUARDAR
	REGRESAR1
	GOTO VERIFICARCAMBIOCONT
	REGRESAR2
	CALL DIBUJAR 
	BTFSS PORTA,0
	GOTO VERIFCARBOTON2
	GOTO AUMENTARUNIDADES
	
	VERIFCARBOTON2
	BTFSS PORTA,1
	GOTO CICLO1
	GOTO DECREMENTARUNIDADES

;----------------------Aumentar unidades----------------
	AUMENTARUNIDADES
	BTFSC PORTA,0
	GOTO AUMENTARUNIDADES

	INCF NUMCONT,1
	INCF R_UNIDADES,1
	DECFSZ R_UNIDADES2,1
	GOTO CICLO1
	GOTO AUMENTARDECENAS



;---------------------Aumentar Decenas----------------
	AUMENTARDECENAS
	CALL RESUNI
	INCF R_DECENAS, 1
	DECFSZ R_DECENAS2,1
	GOTO CICLO1
	GOTO RESETEAR1
	

;--------------------Resetea Contador----------------
	RESETEAR1 
	MOVLW H'0'
	MOVWF R_UNIDADES
	MOVWF R_DECENAS
	MOVWF NUMCONT

	MOVLW H'A'
	MOVWF R_UNIDADES2
	MOVWF R_DECENAS2
	GOTO CICLO1

;-------------------Decrementar Unidades----------------
	DECREMENTARUNIDADES
	BTFSC PORTA,1
	GOTO DECREMENTARUNIDADES

	DECF NUMCONT,1
	MOVF R_UNIDADES ,0 
	BTFSC STATUS, Z
	GOTO DECREMENTARDECENAS
	
	INCF R_UNIDADES2,1
	DECF R_UNIDADES,1
	GOTO CICLO1
;---------------------Decrementar Decenas----------------
	DECREMENTARDECENAS
	MOVF R_DECENAS ,0 
	BTFSC STATUS, Z
	GOTO RESETEAR99

	CALL RESETEAR2
	INCF R_DECENAS2, 1
	DECF R_DECENAS,1
	GOTO CICLO1

;--------------------RESETEAR2--------------------
	RESETEAR2
	MOVLW H'9'
	MOVWF R_UNIDADES
	MOVLW H'1'
	MOVWF R_UNIDADES2
	RETURN
;--------------------RESETEAR99--------------------
	RESETEAR99
	MOVLW H'9'
	MOVWF R_UNIDADES
	MOVWF R_DECENAS
	MOVLW H'99'
	MOVWF NUMCONT

	MOVLW H'1'
	MOVWF R_UNIDADES2
	MOVWF R_DECENAS2


	GOTO CICLO1

;---------------------DIIBUJAR DISPLAYS----------------

	DIBUJAR
	MOVF R_DECENAS,0
	MOVWF PORTB
	
	MOVF R_UNIDADES,0
	MOVWF PORTD
	RETURN

;----------------Resetear Unidades-------------------
	RESUNI
	MOVLW H'0'
	MOVWF R_UNIDADES
	MOVLW H'A'
	MOVWF R_UNIDADES2
	RETURN



;---------------------------VERIFICARCAMBIOCONT-----------------

	VERIFICARCAMBIOCONT
	BTFSS PORTC,0
	GOTO VERIFICARCAMBIO2CONT
	GOTO POSI1

	VERIFICARCAMBIO2CONT
	BTFSS PORTC,1
	GOTO REGRESAR2
	GOTO POSI2

;---------------------------VERIFICARCAMBIOPOS1-----------------

	VERIFICARCAMBIOPOS1
	BTFSS PORTC,1
	GOTO VERIFICARCAMBIO2POS1
	GOTO POSI2

	VERIFICARCAMBIO2POS1
	BTFSS PORTC,2
	GOTO REGRESARPOS1
	GOTO CICLO1



;---------------------------VERIFICARCAMBIOPOS2----------------

	VERIFICARCAMBIOPOS2
	BTFSS PORTC,0
	GOTO VVERIFICARCAMBIO2POS2
	GOTO POSI1

	VVERIFICARCAMBIO2POS2
	BTFSS PORTC,2
	GOTO REGRESARPOS2
	GOTO CICLO1

;-----------------------------POS1-----------------------------
	POSI1
	BTFSC PORTC,0
	GOTO POSI1

	GOTO VERIFICARCAMBIOPOS1
	REGRESARPOS1
	MOVF POS1_UNIDADES,0
	MOVWF PORTD
	MOVF POS1_DECENAS,0
	MOVWF PORTB

	GOTO POSI1

;------------------------POS2------------------------------------
	POSI2
	BTFSC PORTC,1
	GOTO POSI2

	GOTO VERIFICARCAMBIOPOS2
	REGRESARPOS2
	MOVF POS2_UNIDADES,0
	MOVWF PORTD
	MOVF POS2_DECENAS,0
	MOVWF PORTB

	GOTO POSI2


;----------------------VERIFICARGUARDAR--------------------------
	VERIFICARGUARDAR
	BTFSS PORTA,2
	GOTO REGRESAR1
	GOTO GUARDAR


;-----------------------GUARDAR-----------------------
	
	GUARDAR
	BTFSC PORTA,2
	GOTO GUARDAR

	MOVF POS1_UNIDADES,0
	MOVWF POS2_UNIDADES

	MOVF POS1_DECENAS,0
	MOVWF POS2_DECENAS

	MOVF R_UNIDADES,0
	MOVWF POS1_UNIDADES

	MOVF R_DECENAS,0
	MOVWF POS1_DECENAS

	MOVF NUMERO1,0
	MOVWF NUMERO2

	MOVF NUMCONT,0
	MOVWF NUMERO1
	
	GOTO REGRESAR1

;--------------------------------VERIFICAROPERACION-------------------------------------
	VERIFICAROPERACION
	BTFSS PORTA,3
	GOTO VERIFICAROPERACION3
	GOTO CAMBIAR

	VERIFICAROPERACION3
	BTFSS PORTA,5
	GOTO REGRESAR
	GOTO OPERAR


;---------CAMBIAR------------
	CAMBIAR
	BTFSC PORTA,3
	GOTO CAMBIAR

	DECFSZ CUAL_OPERACION,1
	GOTO CS
	GOTO CR

	;CAMBIAR A SUMA
	CS
	MOVLW H'1'
	MOVWF CUAL_OPERACION
	MOVLW H'1'
	MOVWF PORTE
	GOTO REGRESAR

	;CAMBIAR A RESTA
	CR
	MOVLW H'0'
	MOVWF CUAL_OPERACION
	MOVLW H'2'
	MOVWF PORTE
	GOTO REGRESAR




;---------------------------------OPERAR------------------------------

	OPERAR
	BTFSC PORTA,5
	GOTO OPERAR
	
	DECFSZ CUAL_OPERACION,1
	GOTO RESTA
	GOTO SUMA

;------------------------------SUMA----------------------------

	
    SUMA
	MOVLW H'1'
	MOVWF CUAL_OPERACION
	MOVLW H'63'
	MOVWF VALOR_TEMP


	MOVF POS1_UNIDADES,0
	MOVWF RESPUESTA
	MOVF POS2_UNIDADES,0
	ADDWF RESPUESTA,1
	 
	MOVF POS1_DECENAS,0
	MOVWF VALOR_TEMP2
	BTFSC STATUS, Z
	GOTO SUMARDECENAS2
	
	CIC1
	MOVLW H'A'
	ADDWF RESPUESTA,1
	DECFSZ VALOR_TEMP2,1
	GOTO CIC1
	

	SUMARDECENAS2
	MOVF POS2_DECENAS,0
	MOVWF VALOR_TEMP2
	BTFSC STATUS, Z
	GOTO CONTINUAR

	CIC2
	MOVLW H'A'
	ADDWF RESPUESTA,1
	DECFSZ VALOR_TEMP2,1
	GOTO CIC2
	

	CONTINUAR







	MOVF RESPUESTA,0
	SUBWF VALOR_TEMP

	BTFSC STATUS,C
	GOTO MENOR_99
	GOTO MAYOR_99

	MENOR_99
	GOTO GUARDAR_RESPUESTA

	MAYOR_99
	GOTO GUARDAR_RESPUESTA99
	

    TERMINAR_SUMAR
	GOTO CICLO1
	


;--------GUARDAR RESPUESTA99 -------

	GUARDAR_RESPUESTA99
	
	MOVF POS1_UNIDADES,0
	MOVWF POS2_UNIDADES
	MOVF POS1_DECENAS,0
	MOVWF POS2_DECENAS

	MOVLW H'9'
	MOVWF POS1_UNIDADES
	MOVWF POS1_DECENAS

	GOTO CICLO1


;----------------------GUARDAR_RESPUESTA------------------
	GUARDAR_RESPUESTA
	MOVLW H'0'
	MOVWF RESPUESTA_UNIDADES
	MOVWF RESPUESTA_DECENAS
	MOVLW H'A'
	MOVWF RESPUESTA_UNIDADES2
	MOVWF RESPUESTA_DECENAS2
	
	CRS
	CALL SUMAR_UNIDAD_RESPUESTA
	DECFSZ RESPUESTA,1
	GOTO CRS 
	GOTO GUARDAR_RESPUESTA_NO_99

;------SUMAR_UNIDAD_RESPUESTA-----
	SUMAR_UNIDAD_RESPUESTA
	
	INCF RESPUESTA_UNIDADES,1
	DECFSZ RESPUESTA_UNIDADES2,1
	RETURN
	
	MOVLW H'0'
	MOVWF RESPUESTA_UNIDADES
	MOVLW H'A'
	MOVWF RESPUESTA_UNIDADES2

	INCF RESPUESTA_DECENAS, 1
	RETURN



;------------------GUARDAR_RESPUESTA_NO_99---------------
	GUARDAR_RESPUESTA_NO_99
	
	MOVF POS1_UNIDADES,0
	MOVWF POS2_UNIDADES
	MOVF POS1_DECENAS,0
	MOVWF POS2_DECENAS

	MOVF RESPUESTA_UNIDADES,0
	MOVWF POS1_UNIDADES
	MOVF RESPUESTA_DECENAS,0
	MOVWF POS1_DECENAS

	GOTO CICLO1

;-------------------RESTA-----------------
	RESTA

	MOVLW H'0'
	MOVWF CUAL_OPERACION


	MOVF POS1_UNIDADES,0
	MOVWF RESTACONT1
	MOVF POS1_DECENAS,0
	MOVWF VALOR_TEMP2
	BTFSC STATUS, Z
	GOTO SUMARDECENAS22
	CIC11
	MOVLW H'A'
	ADDWF RESTACONT1,1
	DECFSZ VALOR_TEMP2,1
	GOTO CIC11
	

	SUMARDECENAS22
	MOVF POS2_UNIDADES,0
	MOVWF RESTACONT2

	MOVF POS2_DECENAS,0
	MOVWF VALOR_TEMP2
	BTFSC STATUS, Z
	GOTO CONTINUAR2
	CIC22
	MOVLW H'A'
	ADDWF RESTACONT2,1
	DECFSZ VALOR_TEMP2,1
	GOTO CIC22



	CONTINUAR2
	MOVF RESTACONT1,0
	MOVWF RESTACONT11
	MOVF RESTACONT2,0
	MOVWF RESTACONT22


	MOVF RESTACONT2,0
	SUBWF RESTACONT1

	BTFSC STATUS,C
	GOTO NEGATIVO
	GOTO POSITIVO

	NEGATIVO
	GOTO GUARDAR_RESPUESTA_RESTA

	POSITIVO
	GOTO GUARDAR_RESPUESTA00
	
	

;--------------GUARDAR_RESPUESTA00--------------
	GUARDAR_RESPUESTA00
	
	MOVF POS1_UNIDADES,0
	MOVWF POS2_UNIDADES
	MOVF POS1_DECENAS,0
	MOVWF POS2_DECENAS

	MOVLW H'0'
	MOVWF POS1_UNIDADES
	MOVWF POS1_DECENAS

	GOTO CICLO1


;------------------------GUARDAR_RESPUESTA_RESTA-------------------
	GUARDAR_RESPUESTA_RESTA
	MOVLW H'0'
	MOVWF RESPUESTA_UNIDADES
	MOVWF RESPUESTA_DECENAS
	MOVLW H'A'
	MOVWF RESPUESTA_UNIDADES2
	MOVWF RESPUESTA_DECENAS2

	MOVF RESTACONT22,0
	SUBWF RESTACONT11,0
	MOVWF RESPUESTA

	MOVF RESPUESTA,0
	BTFSC STATUS ,Z
	GOTO GUARDAR_RESPUESTA_NO_99

	CRS2
	CALL SUMAR_UNIDAD_RESPUESTA
	DECFSZ RESPUESTA,1
	GOTO CRS2
	GOTO GUARDAR_RESPUESTA_NO_99
	





	End